sudo: required

env:
  - IMAGE_NAME="golang:staging"

services:
- docker

branches:
  only:
    - master

script:
- curl https://raw.githubusercontent.com/GoogleCloudPlatform/runtimes-common/master/structure_tests/ext_run.sh > ext_run.sh
- chmod +x ext_run.sh
- docker build -t "$IMAGE_NAME" -q base/
- ./ext_run.sh -i "$IMAGE_NAME" -v --config test/test_config.json
